### ISSUE TITLE
IMDB Lists not working

### ISSUE THREAD

**Issue by Dire-Pants** [primetime43/PlexPlaylistMaker#1]
Properly connected server via browser API session connection and used the current URL format for IMDB lists on a non-private(public) list.

Trying to generate a playlist not working.

Turned off VPN to made sure it wasn't interfering.

Getting this error:

![Screenshot 2024-06-21 144640](https://github.com/primetime43/PlexPlaylistMaker/assets/83974836/35abd6b8-ab75-4f80-a6b2-f4cc65532389)

**Comment by Dire-Pants** [comment]
If you can confirm to me that functionality is ok, I will continue to troubleshoot my local machine

**Comment by primetime43** [comment]
> Properly connected server via browser API session connection and used the current URL format for IMDB lists on a non-private(public) list.
> 
> 
> 
> Trying to generate a playlist not working.
> 
> 
> 
> Turned off VPN to made sure it wasn't interfering.
> 
> 
> 
> Getting this error:
> 
> 
> 
> ![Screenshot 2024-06-21 144640](https://github.com/primetime43/PlexPlaylistMaker/assets/83974836/35abd6b8-ab75-4f80-a6b2-f4cc65532389)
> 
> 
> 
> 
> 
> 

What's the url you're trying to use? So I can reproduce the issue the same way.

**Comment by Dire-Pants** [comment]
Hello! Sorry for the late reply. The url is listed in the screenshot at the top:

https://www.imdb.com/list/ls506052034

 It was set to Public: On during my troubleshooting.

If this tool works it would save me a lot of manual tedium!

**Comment by primetime43** [comment]
> Hello! Sorry for the late reply. The url is listed in the screenshot at the top:
> 
> https://www.imdb.com/list/ls506052034
> 
> It was set to Public: On during my troubleshooting.
> 
> If this tool works it would save me a lot of manual tedium!

Awesome thanks! I was able to use the url to debug the program and figure out the issue. It should be fixed with the v1.1 release now. I appreciate the bug report!
